### ISSUE TITLE
[Add] Add Apache Cassandra DB to Databases in backend category

### ISSUE THREAD

**Issue by p1utoze** [rupali-codes/LinksHub#1998]
### Site URL

https://cassandra.apache.org/

### Description of the above provided site

Apache Cassandra is a free and open-source, distributed, wide column store, NoSQL database management system designed to handle large amounts of data across many commodity servers, providing high availability with no single point of failure. It is used by some of the famous tech giants like Netflix, Twitter and Amazon (Keyspaces).

### Category

Backend

### Sub Category

database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @p1utoze! :) In the future, please raise an issue before you submit your PR. Once your issue is approved, keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
