### ISSUE TITLE
[OTHER] Missing Report a Bug

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2317]
### What would you like to share or ask?

I was working on the icons component issue and I noticed something strange.

`Report a bug` is missing from the sidebar.

![sidebar](https://github.com/rupali-codes/LinksHub/assets/74038190/4fdbe48d-3d61-4537-b8a1-92965a26617d)

You can view the [figma](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=cyWeHoIr7pJt3LW2-0) here.

@rupali-codes @aftabrehan @CBID2 
What do you think? Did we miss it.

Because I can see the code in Sidebar component
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c3e4008a-d48d-426f-96f2-6203f42179a2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, the report bug button was hidden for normal screens and visible only for large screens since we have "our team" and "saved" buttons in the sidebar. 

But now that we have moved "our team" and "saved" buttons in the header, there is enough space to show report bug button even for normal screens. I believe we only need to remove the last two classes 'hidden tall:flex' of the button and it will work as expected.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, the report bug button was hidden for normal screens and visible only for large screens since we have "our team" and "saved" buttons in the sidebar.
> 
> But now that we have moved "our team" and "saved" buttons in the header, there is enough space to show report bug button even for normal screens. I believe we only need to remove the last two classes 'hidden tall:flex' of the button and it will work as expected.

Okay! Thanks for letting me know.

I will cover it in the same issue then.
