### ISSUE TITLE
[CHORE] add a fixed height on Link Card

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#50]
### What would you like to share or ask?

I just noticed, when card have a long description it's increasing card length, which is not good.

### Specific requirements  
- add fixed length to link card
- hide description if it contains more than 12-15 words

### Additional information

![image](https://user-images.githubusercontent.com/78981177/213429672-bcbb250a-40b6-470e-96c5-37d70a440718.png)

**Comment by PriyansuMaurya** [comment]
Adding fixed height wouldn't fix the problem because sometimes it may happen that people may add more extensive descriptions. so again we have to increase the height of the cards. 

My suggestion would be let's make the card square and make it such that when the description extends the limit it should show **...**
like this 

![Group 2](https://user-images.githubusercontent.com/101447544/213449395-8a8ae0a1-9c60-43c9-8f19-8449ff3ed1e4.jpg)


or (if you don't like it ) instead of **....** we should add **read more** and make it link to that website such that when the user clicks it, he is directed to the website.


![Group 1](https://user-images.githubusercontent.com/101447544/213449417-df949d0a-d9d6-4d79-a9d6-8b33b65c5b19.jpg)

**Comment by AdekeyeAdeniyi** [comment]
Am available if issue is open.

**Comment by rupali-codes** [comment]
@PriyansuMaurya can we make a popup instead, when user clicks on card, then it will show up, containing site name, full description and link.

**Comment by rupali-codes** [comment]
> Am available if issue is open.

yes you can, also suggest us new ideas how can we tackle this instead of hiding description, what else could be done

**Comment by PriyansuMaurya** [comment]
> @PriyansuMaurya can we make a popup instead, when user clicks on card, then it will show up, containing site name, full description and link. 

Logically speaking no!

If the person wants more about it then he will definitely click the button and see its detail. (In case of **......**)

Or in case of **read more**.

**Comment by rupali-codes** [comment]
> > @PriyansuMaurya can we make a popup instead, when user clicks on card, then it will show up, containing site name, full description and link.
> 
> Logically speaking no!
> 
> If the person wants to know more about it then he will definitely click the button and see its detail from the website itself. (In case of **......**)
> 
> Or in case of **read more**.

can we make something like `tooltip` when user clicks on `read more` it will show a `tooltip` containing full description.

**Comment by PriyansuMaurya** [comment]
An Preview would be real nice.
