### ISSUE TITLE
[Feature] Add GitHub fork button

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#774]
### Description

I was inspired by #768, so I’m going to create a fork button to display how many copies LinksHub has. 
**Note:** **I am eager to work on this feature with a GSSOC’23 contributor.**
**Update**: I created the button using [this website](https://buttons.github.io/)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@CBID2 Do you want work on this issue?

**Comment by CBID2** [comment]
> @CBID2 Do you want work on this issue?
> 
> 

Yeah with another GSSOC contributor @rupali-codes.

**Comment by rupali-codes** [comment]
With? Who? 👀

**Comment by CBID2** [comment]
> With? Who? 👀

Just anyone who's eager @rupali-codes lol 😂

**Comment by rupali-codes** [comment]
@CBID2 do you need any help Chrissy?

**Comment by CBID2** [comment]
> @CBID2 do you need any help Chrissy?

Yes @rupali-codes

**Comment by rupali-codes** [comment]
> > > @CBID2 do you need any help Chrissy?
> > 
> > 
> > Yes @rupali-codes
> 
> I will help her, but please give me some time. I have been having exams for the past two days, along with other commitments. I will complete the task by tomorrow. I sincerely apologize for not mentioning the reason earlier.
> 
> Also, @rupali-codes, I wanted to express my interest in becoming a maintainer of LinksHub after GSSoC'23. I have prior experience maintaining organizational repositories and possess the necessary expertise to fulfill the role effectively. I had initially planned to discuss this after GSSoC, but I believe the earlier we address it, the better. I am committed to contributing significantly and earning your trust.

Sure, thanks

**Comment by CBID2** [comment]
@Anmol-Baranwal, we'd love to have you on the team! :)

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, we'd love to have you on the team! :)

Thanks, I am truly honored and glad to hear that.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
There are two approaches to making this possible, depending on your decision. 
Only the first approach, which involves dynamically loading the script in a component using `useEffect`, works. 

Now, you can either suggest the problem with the other approaches, or we can proceed with the first approach.

## First Approach

> works :)

```typescript

... import statements

export const Header: FC<{}> = () => {
  const { toggleNav } = useContext(GlobalContext)

 <-------------------------------ADDED THIS CODE BEGIN------------------------------->
  useEffect(() => {
    const script = document.createElement('script')
    script.src = 'https://buttons.github.io/buttons.js'
    script.async = true
    script.defer = true
    document.head.appendChild(script)
    return () => {
      document.head.removeChild(script)
    }
  }, [])
<-------------------------------ADDED THIS CODE END------------------------------->
  return (
    <header className="fixed top-0 left-0 z-30 row-start-1 row-end-2 flex h-[76px] w-screen items-center justify-between">
      <div className="bg-base-200 relative h-full grow px-8 dark:bg-gray-900 lg:bg-gray-100 lg:dark:bg-[#101623]">
        
        <-------------------------------ADDED THIS CODE BEGIN------------------------------->
        <Link
          className="github-button"
          href="https://github.com/rupali-codes/LinksHub"
          data-icon="octicon-repo-forked"
          data-size="large"
          data-show-count="true"
          aria-label="Fork rupali-codes/LinksHub on GitHub"
        >
          Fork
        </Link>
       <-------------------------------ADDED THIS CODE END------------------------------->
    </header>
  )
}
```

<br>

This dynamically add the script only when it's needed (e.g., in the `Header` component), it allows to defer the loading of the script until it's necessary. This can help reduce the initial load time of your application by avoiding unnecessary script loading for pages that don't use the GitHub Buttons.

If the script is only needed on specific pages or components, dynamically loading it when required can help reduce the initial load time and bundle size for pages that don't use the GitHub Buttons.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/969eb622-c6d1-4e95-a755-81239496d25d)

> It is generally recommended to include scripts dynamically within the components or layout files for better control and compatibility with server-side rendering.

## Second Approach

> In _document.js `failed` :(

I don't know for certain, but one possible reason could be that Next.js does not execute JavaScript code within the `_document.js` file during server-side rendering. Therefore, including the script directly in the `_document.js` file might not work as expected.

If we can include the script directly in the `_document.js` file, it will be loaded and cached by the browser when the page is first rendered. This can improve subsequent page loads since the script will be retrieved from the cache instead of making an additional network request.

## Third Approach

> In _app.js `failed` :(

```typescript
// _app.js
import 'styles/globals.css'
import type { AppProps } from 'next/app'
import GeneralLayout from 'layouts/GeneralLayout'
import { GlobalProvider } from 'context/GlobalContext'
import { Preloader } from 'components/Loader/Preloader'
import { ThemeProvider } from 'next-themes'
import Head from 'next/head' // Import the Head component

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider defaultTheme="dark">
      <GlobalProvider>
        <Preloader backgroundColor="bg-violet-800" color="#8b5cf6" size={40}>
          <GeneralLayout>
            <Component {...pageProps} />
          </GeneralLayout>
        </Preloader>
      </GlobalProvider>

      <Head>
        <script async defer src="https://buttons.github.io/buttons.js"></script>
      </Head>
    </ThemeProvider>
  )
}
```
